In [1]:
import numpy as np

In [5]:
%run cw91.py

[['Profile    Time    Course    Change    Change%    Ref.    Open    Low    High    Volume    Turn    Share']
 ['11B (11BIT)    17 kwi 17:01    391.00    +8.00    (+2.09%)    383.00    383.50    383.00    394.00    12 784    4 994 874    19.034%']
 ['CDR (CDPROJEKT)    17 kwi 17:01    339.50    +5.30    (+1.59%)    334.20    338.30    337.00    344.20    233 059    79 245 368    39.618%']
 ['CIG (CIGAMES)    17 kwi 17:03    0.742    -0.012    (-1.59%)    0.754    0.772    0.730    0.772    1 311 078    971 459    1.855%']
 ['PLW (PLAYWAY)    17 kwi 17:03    387.50    +18.00    (+4.87%)    369.50    374.00    373.00    388.00    33 206    12 661 786    10.638%']
 ['TEN (TSGAMES)    17 kwi 17:02    349.50    +22.50    (+6.88%)    327.00    332.00    330.00    353.50    39 793    13 697 060    28.855%']]


In [6]:
%run cw92.py

[['Profile' 'Time' 'Course' 'Open' 'Low' 'High' 'Turn' 'Share']
 ['11B(11BIT)' '17kwi17:01' '391.00' '383.50' '383.00' '394.00' '4994874'
  '19.034%']
 ['CDR(CDPROJEKT)' '17kwi17:01' '339.50' '338.30' '337.00' '344.20'
  '79245368' '39.618%']
 ['CIG(CIGAMES)' '17kwi17:03' '0.742' '0.772' '0.730' '0.772' '971459'
  '1.855%']
 ['PLW(PLAYWAY)' '17kwi17:03' '387.50' '374.00' '373.00' '388.00'
  '12661786' '10.638%']
 ['TEN(TSGAMES)' '17kwi17:02' '349.50' '332.00' '330.00' '353.50'
  '13697060' '28.855%']]


In [7]:
%run cw93.py

[['Profile' 'Time' 'Course' 'Open' 'Low' 'High' 'Turn' 'Share']
 ['11B(11BIT)' '17kwi17:01' '391.00' '383.50' '383.00' '394.00' '4994874'
  '19.034%']
 ['CDR(CDPROJEKT)' '17kwi17:01' '339.50' '338.30' '337.00' '344.20'
  '79245368' '39.618%']
 ['CIG(CIGAMES)' '17kwi17:03' '0.742' '0.772' '0.730' '0.772' '971459'
  '1.855%']
 ['PLW(PLAYWAY)' '17kwi17:03' '387.50' '374.00' '373.00' '388.00'
  '12661786' '10.638%']
 ['TEN(TSGAMES)' '17kwi17:02' '349.50' '332.00' '330.00' '353.50'
  '13697060' '28.855%']]


In [8]:
%run cw94.py

[['Date,Open,High,Low,Close,Volume']
 ['2020-03-02,305,324.5,283.5,310,64081']
 ['2020-03-03,325.5,340.5,320,340.5,55496']
 ['2020-03-04,324,340.5,315,330,36152']
 ['2020-03-05,344,344,310,315,35992']
 ['2020-03-06,306.5,307,291,305,32539']
 ['2020-03-09,274,291,250,258,79402']
 ['2020-03-10,278,284.5,256,264,35700']
 ['2020-03-11,270,270,238.5,245,60445']
 ['2020-03-12,218,228,196,197,94031']
 ['2020-03-13,210,229,198.8,211,100412']
 ['2020-03-16,205,248,197.8,240.5,50659']
 ['2020-03-17,245,269,232.5,264,99480']
 ['2020-03-18,264,280,251,270,70136']
 ['2020-03-19,267,280,267,279.5,30732']
 ['2020-03-20,297.5,307,280,280.5,43426']
 ['2020-03-23,274,289,258,285,37098']
 ['2020-03-24,305,309,296.5,309,31939']
 ['2020-03-25,313,330,295,304,46724']
 ['2020-03-26,300,309,295.5,300,27213']
 ['2020-03-27,302,306.5,290,296,13466']
 ['2020-03-30,299,300,287,300,10316']
 ['2020-03-31,302.5,309,302,306.5,15698']]


In [9]:
%run cw95.py

[[   305.     324.5    283.5    310.   64081. ]
 [   325.5    340.5    320.     340.5  55496. ]
 [   324.     340.5    315.     330.   36152. ]
 [   344.     344.     310.     315.   35992. ]
 [   306.5    307.     291.     305.   32539. ]
 [   274.     291.     250.     258.   79402. ]
 [   278.     284.5    256.     264.   35700. ]
 [   270.     270.     238.5    245.   60445. ]
 [   218.     228.     196.     197.   94031. ]
 [   210.     229.     198.8    211.  100412. ]
 [   205.     248.     197.8    240.5  50659. ]
 [   245.     269.     232.5    264.   99480. ]
 [   264.     280.     251.     270.   70136. ]
 [   267.     280.     267.     279.5  30732. ]
 [   297.5    307.     280.     280.5  43426. ]
 [   274.     289.     258.     285.   37098. ]
 [   305.     309.     296.5    309.   31939. ]
 [   313.     330.     295.     304.   46724. ]
 [   300.     309.     295.5    300.   27213. ]
 [   302.     306.5    290.     296.   13466. ]
 [   299.     300.     287.     300.   1

In [10]:
%run cw96.py

[  283.14   295.25   268.69   282.3  48688.05]


In [11]:
%run cw97.py

[[   305.     324.5    283.5    310.   64081.      41. ]
 [   325.5    340.5    320.     340.5  55496.      20.5]
 [   324.     340.5    315.     330.   36152.      25.5]
 [   344.     344.     310.     315.   35992.      34. ]
 [   306.5    307.     291.     305.   32539.      16. ]
 [   274.     291.     250.     258.   79402.      41. ]
 [   278.     284.5    256.     264.   35700.      28.5]
 [   270.     270.     238.5    245.   60445.      31.5]
 [   218.     228.     196.     197.   94031.      32. ]
 [   210.     229.     198.8    211.  100412.      30.2]
 [   205.     248.     197.8    240.5  50659.      50.2]
 [   245.     269.     232.5    264.   99480.      36.5]
 [   264.     280.     251.     270.   70136.      29. ]
 [   267.     280.     267.     279.5  30732.      13. ]
 [   297.5    307.     280.     280.5  43426.      27. ]
 [   274.     289.     258.     285.   37098.      31. ]
 [   305.     309.     296.5    309.   31939.      12.5]
 [   313.     330.     295.    

In [12]:
%run cw98.py

[[  305.    324.5   283.5   310.  64081.     41. ]
 [  325.5   340.5   320.    340.5 55496.     20.5]
 [  324.    340.5   315.    330.  36152.     25.5]
 [  344.    344.    310.    315.  35992.     34. ]
 [  306.5   307.    291.    305.  32539.     16. ]
 [  305.    309.    296.5   309.  31939.     12.5]
 [  313.    330.    295.    304.  46724.     35. ]
 [  302.5   309.    302.    306.5 15698.      7. ]]


In [13]:
%run cw99.py

[[   210.     229.     198.8    211.  100412.      30.2]
 [   245.     269.     232.5    264.   99480.      36.5]
 [   218.     228.     196.     197.   94031.      32. ]
 [   274.     291.     250.     258.   79402.      41. ]
 [   264.     280.     251.     270.   70136.      29. ]
 [   305.     324.5    283.5    310.   64081.      41. ]
 [   270.     270.     238.5    245.   60445.      31.5]
 [   325.5    340.5    320.     340.5  55496.      20.5]
 [   205.     248.     197.8    240.5  50659.      50.2]
 [   313.     330.     295.     304.   46724.      35. ]]


In [14]:
%run cw100.py

[[   305.     324.5    283.5    310.   64081.      41.       1. ]
 [   325.5    340.5    320.     340.5  55496.      20.5      1. ]
 [   324.     340.5    315.     330.   36152.      25.5      1. ]
 [   344.     344.     310.     315.   35992.      34.       0. ]
 [   306.5    307.     291.     305.   32539.      16.       0. ]
 [   274.     291.     250.     258.   79402.      41.       0. ]
 [   278.     284.5    256.     264.   35700.      28.5      0. ]
 [   270.     270.     238.5    245.   60445.      31.5      0. ]
 [   218.     228.     196.     197.   94031.      32.       0. ]
 [   210.     229.     198.8    211.  100412.      30.2      1. ]
 [   205.     248.     197.8    240.5  50659.      50.2      1. ]
 [   245.     269.     232.5    264.   99480.      36.5      1. ]
 [   264.     280.     251.     270.   70136.      29.       1. ]
 [   267.     280.     267.     279.5  30732.      13.       1. ]
 [   297.5    307.     280.     280.5  43426.      27.       0. ]
 [   274. 