In [13]:
import numpy as np

In [14]:
tab = np.arange(0,12)
tab = np.ndarray.reshape(tab,(3,4))

np.save('array.npy',tab)

B = np.load('array.npy')
print(B)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [15]:
tab = np.arange(12)
tab = np.ndarray.reshape(tab,(3,4))

np.savetxt("array.txt",tab,fmt="%0.2f")

B = np.loadtxt("array.txt")
print(B)

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]


In [16]:
tab = np.arange(12)
tab = np.ndarray.reshape(tab,(-1,4))

lista = tab.tolist()
print(lista)

[[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]]


In [17]:
tab = np.arange(12).reshape(-1,4)

print(tab[[-1,1,0]])
#2 roz odwrocenie tab
print(tab[::-1])

[[ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]
[[ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]


In [18]:
tab = np.full((4,4),1,dtype=float)
print(tab)
tab = np.pad(tab,pad_width=1,mode="constant",constant_values=0)
print()
print(tab)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

[[0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [19]:
tab = np.zeros((6,6),dtype=int)
print(tab)

tab[::2,::2] = 10
tab[1::2,::2] = 5
print(tab)

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
[[10  0 10  0 10  0]
 [ 5  0  5  0  5  0]
 [10  0 10  0 10  0]
 [ 5  0  5  0  5  0]
 [10  0 10  0 10  0]
 [ 5  0  5  0  5  0]]


In [20]:
A = np.arange(12).reshape(-1, 4)
B = np.array([[4, 3, 7, 2], [0, 5, 2, 6]])

C = np.append(arr=A,values=B,axis=0)

print(C)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 4  3  7  2]
 [ 0  5  2  6]]


In [21]:
A = np.arange(8).reshape(-1, 4)
B = np.array([[9, 10, 11, 3], [2, 8, 0, 9]])

C = np.intersect1d(A,B)
print(C)

[0 2 3]


In [22]:
#tworzenie tab 1
A = np.array([[5, 1, 2, 1, 2],
       [9, 1, 9, 7, 5],
       [4, 1, 5, 7, 9]])
#tworzenie tab za pomoca random

np.random.seed(10)
B = np.random.randint(1,10,(3,5))

print(np.unique(A))

[1 2 4 5 7 9]


In [23]:
A = np.array([[0.4, 0.3, 0.3], [0.1, 0.1, 0.8], [0.2, 0.5, 0.3]])

#troche inaczej
for i in range(len(A)):
    print(np.argmax(A[i]))

#roz
print(np.argmax(A,axis=1))

0
2
1
[0 2 1]
