In [7]:
import numpy as np

In [8]:
A = np.array([[4, 2, 1],
              [6, 4, 2]])
print(A)
print(np.expand_dims(A,axis=0))

[[4 2 1]
 [6 4 2]]
[[[4 2 1]
  [6 4 2]]]


In [9]:
np.random.seed(42)

image = np.random.randint(0,256,(200,300,3),dtype=np.uint8)

print(image)

[[[102 220 225]
  [ 95 179  61]
  [234 203  92]
  ...
  [ 41  27  87]
  [102 225  65]
  [170   0 238]]

 [[169 170 213]
  [159  44 250]
  [224 206  61]
  ...
  [162 118  77]
  [228  67  21]
  [ 68  30  64]]

 [[237  26 118]
  [ 62 157 198]
  [  1 151  37]
  ...
  [218 189  51]
  [193 250 243]
  [235  34 180]]

 ...

 [[116 102 228]
  [ 29  75  71]
  [156 133  53]
  ...
  [ 93  45  68]
  [124 238  76]
  [184 185 202]]

 [[216 202 116]
  [146 168 132]
  [236  80  45]
  ...
  [169 145 212]
  [123  50  70]
  [ 11  43  62]]

 [[ 32  52  65]
  [155   2  86]
  [ 83 240  27]
  ...
  [ 30  57 175]
  [ 72  83 171]
  [ 40 114 195]]]


In [10]:
image = np.random.randint(0,256,(200,300,3),dtype=np.uint8)

image_extended = np.expand_dims(image,axis=0)

print(image_extended)

[[[[145  30 244]
   [107   6 122]
   [201  42  86]
   ...
   [182 113 173]
   [140 196 105]
   [123  60 198]]

  [[221  40 190]
   [175  36 108]
   [ 33   0 106]
   ...
   [ 75 169  71]
   [218 180 159]
   [ 88  16   4]]

  [[141 115 148]
   [211  17 146]
   [118 201  37]
   ...
   [ 10 168 141]
   [136 119 180]
   [134 202  48]]

  ...

  [[105 148  18]
   [178 143 146]
   [249 136  32]
   ...
   [ 80  45 210]
   [182 138  93]
   [ 93 176 230]]

  [[  8  92  85]
   [105 188  47]
   [188 219 100]
   ...
   [117 202 126]
   [171 254  58]
   [ 60 227 231]]

  [[ 90  77 134]
   [121 220 235]
   [ 64 117 152]
   ...
   [ 60 122  47]
   [110 218 233]
   [233  85  89]]]]


In [11]:
image1 = np.random.randint(
    low=0, high=256, size=(200, 300, 3), dtype=np.uint8
)
image2 = np.random.randint(
    low=0, high=256, size=(200, 300, 3), dtype=np.uint8
)

image1_extended = np.expand_dims(image1,axis=0)
image2_extended = np.expand_dims(image2,axis=0)

images = np.append(image1_extended,image2_extended,axis=0)

print(images)

[[[[ 41 115 118]
   [ 84 233 122]
   [  9 233 198]
   ...
   [ 37  99 209]
   [211 120 126]
   [ 59  79  35]]

  [[136 156 232]
   [107 217 177]
   [129 224  85]
   ...
   [132  46 214]
   [107 200 163]
   [121  45 198]]

  [[ 58  69 203]
   [ 20  13 211]
   [254 145  72]
   ...
   [  6 183 128]
   [159 139  20]
   [217 117  31]]

  ...

  [[178  96 176]
   [178 151  78]
   [175 147 177]
   ...
   [169 200  37]
   [  9 171  29]
   [145 143  28]]

  [[189 185 126]
   [ 59  76 205]
   [  9 136  25]
   ...
   [ 62  31 235]
   [104 133 186]
   [154  50 165]]

  [[157 209 251]
   [181 230  48]
   [ 21 223 136]
   ...
   [ 76  88 111]
   [211 188  36]
   [ 23 111 239]]]


 [[[ 81  84 180]
   [239 195  87]
   [ 10 247 246]
   ...
   [ 49 136  91]
   [136 192 105]
   [  4 122 161]]

  [[121 115 195]
   [ 18   3 184]
   [253 169 244]
   ...
   [ 92 136 206]
   [ 89  89 113]
   [184   1  81]]

  [[198 236  19]
   [210  50 104]
   [ 12  47 217]
   ...
   [205  24 154]
   [241 227 167]
   [208 134

In [12]:
A = np.array([[[1, 2, 3],
               [6, 3, 2]]])

A = np.squeeze(A,axis=0)
print(A)

[[1 2 3]
 [6 3 2]]


In [13]:
A = np.array([[0.4], [0.9], [0.5], [0.6]])

print(np.squeeze(A,axis=1))

[0.4 0.9 0.5 0.6]


In [14]:
A = np.arange(12).reshape(-1,4)

print(A[:,::-1])

[[ 3  2  1  0]
 [ 7  6  5  4]
 [11 10  9  8]]


In [15]:
tab = np.arange(12).reshape(-1,4)

print(tab[::-1,::-1])

[[11 10  9  8]
 [ 7  6  5  4]
 [ 3  2  1  0]]


In [16]:
np.random.seed(42)

image = np.random.randint(0,256,(10, 10, 3),dtype=np.uint8)


print(image[:,:,0])

[[102  95 234   3  14  46  99 212 188 153]
 [203 214 121 114 239 244  74  14 145 184]
 [116  85 226 235 151 181 160   6  52  14]
 [ 76 233 235 213  68 219 129   0 140 147]
 [ 20  46  19 209  57 156  86  24 235 110]
 [231 254 218 134 162  73 169  35 242 253]
 [187 249 201 231 189 116  49  74 189 158]
 [ 29   7  54 131 181 123 248 119 228  13]
 [ 50 155  40 120  72 115 167  85 131 242]
 [ 52 169  13 144 243 167   8  77  22  10]]


In [17]:

image = np.random.randint(0,256,(10, 10, 3),dtype=np.uint8)

result = image[:5,:5,:]
print(result)

[[[129 219  27]
  [ 59  83 229]
  [ 41 175  91]
  [216 179  61]
  [110 213 173]]

 [[195 126   7]
  [ 67  76 213]
  [174 175 205]
  [  8  34 160]
  [ 97  44 205]]

 [[103  15 155]
  [169 131  93]
  [ 95 193   1]
  [ 76 204  79]
  [253   3 215]]

 [[ 84 145  53]
  [159  82  47]
  [220  37   4]
  [  8 190 178]
  [ 54 248 145]]

 [[201 144  40]
  [101 189 103]
  [ 19 229 227]
  [131  57 237]
  [ 13 249  15]]]
