In [2]:
import numpy as np

In [3]:
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 4.99],
              [14.99, 2.39, 7.29]])

C = np.sort(A,axis=1)
B = np.sort(A,axis=0)
print(C)
print(B)

[[ 3.49  4.99  9.99]
 [ 1.99  4.99  9.99]
 [ 2.39  7.29 14.99]]
[[ 1.99  2.39  4.99]
 [ 4.99  3.49  7.29]
 [14.99  9.99  9.99]]


In [4]:
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 4.99],
              [14.99, 2.39, 7.29]])

print(A[A>8])


[ 9.99  9.99 14.99]


In [5]:
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 14.99],
              [14.99, 2.39, 7.29]])

B = np.where(A > 10,10,A)
print(B)

[[ 4.99  3.49  9.99]
 [ 1.99  9.99 10.  ]
 [10.    2.39  7.29]]


In [6]:
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 14.99],
              [14.99, 2.39, 7.29]])

print(np.ravel(A))

[ 4.99  3.49  9.99  1.99  9.99 14.99 14.99  2.39  7.29]


In [7]:
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 14.99],
              [14.99, 2.39, 7.29]])

B = np.zeros_like(A,dtype=float)
print(B)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [8]:
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 14.99],
              [14.99, 2.39, 7.29]])

B = np.full_like(A,9.99)
print(B)

[[9.99 9.99 9.99]
 [9.99 9.99 9.99]
 [9.99 9.99 9.99]]


In [9]:
A = np.tri(5,5,0,float)
print(A)

[[1. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 0.]
 [1. 1. 1. 1. 1.]]


In [10]:
np.random.seed(10)
A = np.random.randint(1,10,(2,3,4))
print(A)

[[[5 1 2 1]
  [2 9 1 9]
  [7 5 4 1]]

 [[5 7 9 2]
  [9 5 2 4]
  [7 6 4 7]]]


In [11]:
image = np.random.randint(0,256,(200,300),dtype=np.uint8)

print(image)

[[ 30 239 192 ... 146 172 101]
 [ 97 251  31 ...  83 122  81]
 [161 247 231 ... 119 196  16]
 ...
 [ 68  38 169 ...  45 255  91]
 [ 67  56 130 ... 173  83 190]
 [232  47  18 ... 205 154  55]]


In [12]:
image = np.random.randint(0,256,(200,300),dtype=np.uint8)

image_sorted = np.sort(image,axis=1)

print(image_sorted)

[[  1   2   3 ... 253 254 254]
 [  0   1   1 ... 255 255 255]
 [  0   1   2 ... 253 253 254]
 ...
 [  0   0   0 ... 254 255 255]
 [  1   1   2 ... 254 255 255]
 [  2   3   3 ... 252 252 253]]
